-- Schéma initial de SupportDesk.
--
-- Les identités clients ne sont PAS ici : elles vivent dans le CRM legacy et sont lues
-- en SOAP au lot 5. La base ne connaît qu'une référence, crm_client_ref.

CREATE TABLE agent (
    username      VARCHAR(64)  PRIMARY KEY,
    nom_complet   VARCHAR(128) NOT NULL,
    niveau        VARCHAR(32),
    equipe        VARCHAR(64),
    actif         BOOLEAN      NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE agent IS
    'Agents de support. Alignés sur les utilisateurs Keycloak portant le rôle AGENT.';

CREATE TABLE ticket (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference              VARCHAR(32)  NOT NULL UNIQUE,
    sujet                  VARCHAR(80)  NOT NULL,
    description            TEXT         NOT NULL,
    categorie              VARCHAR(20)  NOT NULL,
    statut                 VARCHAR(20)  NOT NULL,
    priorite               VARCHAR(20)  NOT NULL,
    -- Référence du compte propriétaire. C'est SUR CETTE COLONNE que porte la
    -- vérification de propriétaire du lot 4 : un CLIENT ne lit que ses lignes.
    crm_client_ref         VARCHAR(32)  NOT NULL,
    auteur_username        VARCHAR(64)  NOT NULL,
    assigne_a              VARCHAR(64)  REFERENCES agent (username),
    cree_le                TIMESTAMPTZ  NOT NULL,
    derniere_activite_le   TIMESTAMPTZ  NOT NULL,
    derniere_activite_par  VARCHAR(64),
    echeance_sla_le        TIMESTAMPTZ,
    premiere_reponse_le    TIMESTAMPTZ,
    version                BIGINT       NOT NULL DEFAULT 0,

    -- La base ne fait pas confiance à l'application : les énumérations sont contraintes
    -- ici aussi. Une migration future qui ajoute un statut devra passer par ici.
    CONSTRAINT ck_ticket_statut    CHECK (statut IN ('OUVERT', 'EN_COURS', 'RESOLU', 'FERME')),
    CONSTRAINT ck_ticket_priorite  CHECK (priorite IN ('BASSE', 'NORMALE', 'HAUTE')),
    CONSTRAINT ck_ticket_categorie CHECK (categorie IN ('FACTURATION', 'ACCES', 'ANOMALIE', 'EVOLUTION', 'AUTRE'))
);

-- L'index qui sert la liste : filtre par compte, tri par activité décroissante.
CREATE INDEX idx_ticket_client_activite ON ticket (crm_client_ref, derniere_activite_le DESC);
CREATE INDEX idx_ticket_statut          ON ticket (statut);
CREATE INDEX idx_ticket_assigne         ON ticket (assigne_a);

CREATE TABLE commentaire (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id        BIGINT       NOT NULL REFERENCES ticket (id) ON DELETE CASCADE,
    auteur_username  VARCHAR(64)  NOT NULL,
    auteur_type      VARCHAR(20)  NOT NULL,
    contenu          TEXT         NOT NULL,
    -- INTERNE ne doit jamais atteindre un client. Le filtrage se fait dans la requête,
    -- pas au mapping : une note interne ne doit pas même être chargée pour un CLIENT.
    visibilite       VARCHAR(20)  NOT NULL,
    cree_le          TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_commentaire_visibilite  CHECK (visibilite IN ('PUBLIC', 'INTERNE')),
    CONSTRAINT ck_commentaire_auteur_type CHECK (auteur_type IN ('CLIENT', 'AGENT'))
);

CREATE INDEX idx_commentaire_ticket ON commentaire (ticket_id, cree_le);

CREATE TABLE evenement_ticket (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id        BIGINT       NOT NULL REFERENCES ticket (id) ON DELETE CASCADE,
    type             VARCHAR(32)  NOT NULL,
    auteur_username  VARCHAR(64)  NOT NULL,
    detail           VARCHAR(255) NOT NULL,
    cree_le          TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_evenement_type CHECK (type IN (
        'CREATION', 'ASSIGNATION', 'CHANGEMENT_STATUT',
        'CHANGEMENT_PRIORITE', 'REPONSE_CLIENT', 'NOTE_INTERNE'))
);

CREATE INDEX idx_evenement_ticket ON evenement_ticket (ticket_id, cree_le DESC);
